services:
  pgdatabase:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: energy_consumption
    ports:
      - "5432:5432"
    volumes:
      - etl_energy_consumption:/var/lib/postgres/data
    networks:
      - energy_consumption_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@localhost"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - pgdatabase
    networks:
      - energy_consumption_network
  etl:
    build: .
    restart: on-failure
    depends_on:
      - pgdatabase
    networks:
      - energy_consumption_network

volumes:
  etl_energy_consumption:
  pgadmin-data:

networks:
  energy_consumption_network: